### ISSUE TITLE
Select and install test suite

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/greenhouse#1]
I'm very partial to rspec. Any objections?

**Comment by Exellin** [comment]
Rspec is the only test suite I have used on my own so I'm ok with it.

**Comment by pachonk** [comment]
I believe `rspec` most popular, so it probably makes most sense to use for the people trying to get their first jobs.
@brandondees can probably make the argument they're equal, I'm not sure the actual usage metrics.

**Comment by Exellin** [comment]
Also how do you like to generate data for tests?  I've used factory girl and faker in the past and enjoy it.

**Comment by pachonk** [comment]
I use FactoryGirl and faker for (most) tests.

**Comment by Exellin** [comment]
also I use guard to autmatically run tests on file save.  Do you use this as well / want it in this project?

**Comment by pachonk** [comment]
I use guard-rspec and as long long as it's a vanilla install (until discussed otherwise) I'm cool with it.
Should probably be in a separate PR from the initial vanilla rspec install in order to give us the ability to discuss it further.
@Exellin Would you be willing to install rspec and PR that change?

**Comment by Exellin** [comment]
yeah i can do that.

**Comment by pachonk** [comment]
Cool beans, thanks!
Just make sure to keep initial Pr vanilla and we can iterate on it after the fact. It makes the git-blame very apparent what the "default" settings are :dancer:
