### ISSUE TITLE
Which Javascript framework do we want to use?

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/greenhouse#5]
We can also go vanilla or use a microframework like snuggsi written by @snuggs

**Comment by Exellin** [comment]
I think after the call we decided we wouldn't use a javascript framework in order to keep this project more simple and entry level since none of us had any experience using a framework.

**Comment by pachonk** [comment]
Yeah, and this allows us to use bits and pieces off of snuggsi (cc @snuggs) too!

**Comment by sanchez2210** [comment]
I vote for no framework too! Got some exp with Ember-RailsAPI but that might be too complicated. Any thoughts on vue.js? Is it also meant for one-page sites?

**Comment by pachonk** [comment]
@sanchez2210 The whole thing is that these major frameworks take away a lot of the need for rails elements.

**Comment by sanchez2210** [comment]
True, I've been looking for a while for some components-oriented framework. Where you can just add the elements you need. I believe React might be the one that fits the most into that description?

**Comment by pachonk** [comment]
Let's get some votes on this so we can close this out.

All in favor of no framework, add a :+1: reaction, all opposed :-1:

**Comment by brandondees** [comment]
Let me suggest creating some separate / independent project ideas that revolve around practicing with individual frontend frameworks. I know some folks will be looking for opportunities to build something with them for job-seeking purposes, but if the emphasis is rails i'd rather steer clear.

**Comment by brandondees** [comment]
maybe once one or more rails app MVPs are built out, there can be an API-only variation of those to work on as the backend for any number of client apps to consume

**Comment by pachonk** [comment]
I'm going to close this out for now.
We discussed over video chat this piece and we really want to put emphasis on Ruby/RoR and something like Angular or React would make it more towards an API only app.

**Comment by snuggs** [comment]
@pachonk SPRINKLES of JS....not frameworks will leave you in a nice place to grow into a framework if that's what you want.
