### ISSUE TITLE
Install FactoryGirl and Faker

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/greenhouse#7]
If we want it, which I assume we do.

**Comment by sanchez2210** [comment]
Is FactoryGirl substantially better than fixtures?

**Comment by pachonk** [comment]
Different use cases. I tend to use both.

**Comment by sanchez2210** [comment]
Will Install now then. See no reason to not learn how to use it

**Comment by pachonk** [comment]
Looks like @Exellin submitted a PR.
