### ISSUE TITLE
Install guard-rspec

### ISSUE THREAD

**Issue by pachonk** [emerald-rubies/greenhouse#8]
If we want it, which I assume we do.

**Comment by dendenvitorio** [comment]
Hi Alex, can we just make it as a requirement to install? so everyone would be uniform as to what we are installing and what not.

**Comment by pachonk** [comment]
@dendenvitorio By "install guard-rspec" I mean adding it to the gemfile and PRing that change to ensure everyone has the same gems available within the context of this project.

**Comment by Exellin** [comment]
I'm on this right now as well
